trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps: 
- bash: |
    set -x
    set -e
    ###########################################################################
    # Boilerplate
    ###########################################################################
    
    #echo "Examining pipeline variables:"
    #az pipelines variable list --pipeline-name=vault-pipeline

    wget --quiet https://releases.hashicorp.com/vault/1.9.0/vault_1.9.0_linux_amd64.zip
    unzip vault_1.9.0_linux_amd64.zip 
    install -m 755 vault /usr/local/bin/vault
  
    #VAL=$(vault kv get -format=json kv/test | jq -r .data.data.foo)
    #echo $VAL

    #az pipelines variable update --pipeline-name=vault-pipeline --name APPROLE_SECRET --value=123456

    # Login with AppRole from env vars
    export VAULT_TOKEN=$(vault write -field=token auth/approle/login \
                           role_id=$APPROLE_ID secret_id=$APPROLE_SECRET_ID)
    vault token lookup

    # Generate a new secret ID
    NEW_SECRET=$(vault write -field=secret_id -f auth/approle/role/vault-pipeline/secret-id)
    
    # Save the new AppRole secret ID back into the pipeline for next time
    echo "Rotating to new secret_id: $NEW_SECRET "
    az pipelines variable update --pipeline-name=vault-pipeline --name=APPROLE_SECRET_ID --value=$NEW_SECRET

    ###########################################################################
    # Do pipeline work here
    ###########################################################################
    

    # Retrieve secrets from Vault
    vault kv get secret/vault-pipeline/test



    ###########################################################################
    # Clean up
    ###########################################################################
    
    # Revoke token when done
    vault token revoke -self

  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
  displayName: 'Vault'
